apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: multiple-paths-etsy
  namespace: default
spec:
  virtualhost:
    fqdn: dev-ml-platform.etsycloud.com
    rateLimitPolicy:
      admission:
        samplingwindow: 10
        successthreshold: 10
        aggression: 10
  routes:
    - conditions:
      - prefix: /  # matches everything else
      services:
        - name: s1
          port: 80
    - conditions:
      - prefix: /blog  # matches `multi-path.bar.com/blog` or `multi-path.bar.com/blog/*`
      pathRewritePolicy:
        replacePrefix:
          - prefix: /blog
            replacement: /
      requestHeadersPolicy:
        set:
          - name: prevRoute
            value: blog
      services:
        - name: s2
          port: 80
